#!/bin/bash

SOLETTA_PACKAGE=soletta/PKGBUILD
SOLETTA_SPEC=soletta/PKGBUILD.spec

SOLETTA_GIT_PACKAGE=soletta-git/PKGBUILD
SOLETTA_GIT_SPEC=soletta-git/PKGBUILD.spec

cat common.spec > $SOLETTA_PACKAGE
cat $SOLETTA_SPEC >> $SOLETTA_PACKAGE

cat common.spec > $SOLETTA_GIT_PACKAGE
cat $SOLETTA_GIT_SPEC >> $SOLETTA_GIT_PACKAGE
